### PR TITLE
Removed dlig tags from Old Hungarian font because make spelling problems and resolve forms "ab" ligature (rtl and ltr) . See: Issue:#1776

### PR DESCRIPTION
**Pull request by Kixidevel**
On branch remove-dlig-cases
 Changes to be committed:
	modified:   hinted/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
	modified:   phaseIII_only/hinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
	modified:   phaseIII_only/unhinted/otf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.otf
	modified:   phaseIII_only/unhinted/ttf/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf
	modified:   unhinted/NotoSansOldHungarian/NotoSansOldHungarian-Regular.ttf

### CODE REVIEW

**Comment by Kixidevel** [comment]
@googlebot  I signed it!

**Comment by Kixidevel** [comment]
@marekjez86 @google-admin 
Please adopt this pull request. It is the patch for Issue #1776.
If You need, I upload explainer pdf document with Old Hungarian letter symbols.

**Comment by Kixidevel** [comment]
The document, that visualise the problem.
[exclaim_dlig.pdf](https://github.com/googlefonts/noto-fonts/files/4844580/exclaim_dlig.pdf)

**Comment by Kixidevel** [comment]
@marekjez86 @google-admin 
Are there any problems to merge it?

**Comment by anthrotype** [comment]
this repository only holds binary fonts. If there are any issues these should be fixed in the source files in https://github.com/googlefonts/noto-source repository.

**Comment by Kixidevel** [comment]
@anthrotype
Yes, there are binaries. Could you tell me, which noncommercial font editor can I use?
Or could I generate sourcecode from this font?
Which format do you use? I work before only fontforge.
Thanks

**Comment by twardoch** [comment]
The .glyphs file format is [documented](https://github.com/schriftgestalt/GlyphsSDK/blob/master/GlyphsFileFormat.md), you can edit it in any text editor. 

You can use [fontmake](https://github.com/googlefonts/fontmake) to convert .glyphs to .designSpace+.ufo, then open and edit the .ufo in FontForge, write .ufo back and use fontmake to export  .designSpace+.ufo into final fonts.

To edit the .glyphs files, you can also use the trial version of [FontLab 7](https://fontlab.com/) that runs on macOS, on Windows and on Linux with Wine, and you can use [Glyphs](https://glyphsapp.com/) that runs on macOS.

**Comment by twardoch** [comment]
To guarantee minimal changes for a good PR, the best method would be to edit the .glyphs file in a text editor

**Comment by Kixidevel** [comment]
I did metge request to Noto Source. I hope, then will that be done

**Pull request closed without merging**
